import tiktoken
enc=tiktoken.encoding_for_model("gpt-4o-mini")
#Inspect Tokens
# here we are using the tiktoken library to encode a sample text into tokens, and then we print the original text, the list of tokens, the number of tokens, and the decoded tokens to verify that they match the original text.
# sample_text = "Agentic AI agents can plan, reason, and use tools."
# tokens =enc.encode(sample_text)

# print(f"Text: {sample_text}")
# print(f"Tokens: {tokens}")
# print(f"Number of tokens: {len(tokens)}")
# print(F"Decoded tokens:", [enc.decode([t]) for t in tokens])



# Compare token lenght across texts 
# we are comparing the token lengths of different sentences to see how the choice of words and emojis affects the number of tokens generated by the model. This can help us understand how different inputs may impact the model's processing and response generation.
sentences = [   "AI is amazing.",
    "Artificial Intelligence is amazing.",
    "AI is 🔥."
]
for sentence in sentences:
    t=enc.encode(sentence)
    print(f"Text: {sentence}\nTokens: {len(t)} - {t}\n")
    print(f"Decoded Tokens: {[enc.decode([token]) for token in t]}\n")  
 

 # Gnenerate Embeddings

# import os
# from dotenv import load_dotenv
# from openai import OpenAI
# load_dotenv()

# client = OpenAI()

# texts = ["Agentic AI course", "Autonomous agents", "Bananas are yellow","Agentic AI"]

# embeddings = []

# for text in texts:
#     response = client.embeddings.create(
#         model="text-embedding-3-small",
#         input=text # we are creating embeddings for each text in the list using the OpenAI API. The model "text-embedding-3-small" is specified for generating the embeddings, and the input is the text we want to convert into a vector representation. The resulting embedding vector is then stored in the embeddings list, and we print the length of the vector to confirm that it has been generated correctly.
#     )
#     vector = response.data[0].embedding
#     embeddings.append(vector)
#     # print(f"{text}: vector length: {len(vector)}")

# import matplotlib.pyplot as plt
# from sklearn.decomposition import PCA
 
# pca = PCA(n_components=2)
# points = pca.fit_transform(embeddings)
 
# plt.figure(figsize=(6,6))
# for i, txt in enumerate(texts):
#     plt.scatter(points[i,0], points[i,1])
#     plt.text(points[i,0]+0.02, points[i,1]+0.02, txt)
 
# plt.title("Embedding Visualization (PCA 2D)")
# plt.show()

# from sklearn.metrics.pairwise import cosine_similarity
 
# sim = cosine_similarity([embeddings[2]], embeddings)
# print("Similarity scores:", sim)