import os
from xmlrpc import client
from dotenv import load_dotenv
from openai import OpenAI   
load_dotenv()

client = OpenAI()   

#Helper function to run a chat cycle with the LLM. This function takes a list of messages as input, where each message is a dictionary containing the role (e.g., "user" or "assistant") and the content of the message. The function then calls the OpenAI API to create a chat completion using the specified model ("gpt-4o-mini") and returns the content of the generated response. This allows us to have a conversation with the language model by providing it with a series of messages and receiving its response based on those messages.
def chat_cycle(messages):
    response = client.chat.completions.create( 
        model="gpt-5-mini",
        messages=messages
    )
    return response.choices[0].message.content
# coice[0] is used to access the first choice in the response, and .message.content is used to extract the content of the message generated by the model. This allows us to retrieve the actual text response from the language model after it processes the input messages.
# structure of response is 
# {
#   "id": "chatcmpl-123",
#   "object": "chat.completion",
#   "created": 1677652288,
#   "model": "gpt-4o-mini",
#   "choices": [
#     {
#       "index": 0,
#       "message": {
#         "role": "assistant",
#         "content": "Hello! I am your AI agent."
#       },
#       "finish_reason": "stop"
#     }
#   ]
# }
# to have choice[1] you need to expect multiple responses from the model, which can be done by setting the n parameter in the API call to a value greater than 1. For example, if you set n=2, you would receive two choices in the response, and you could access them using choices[0] and choices[1]. However, in the current implementation, we are only requesting one response (the default), so we only have access to choices[0].

## Single Turn Conversation
# messages = [
#     {"role": "user", "content": "What is Agentic AI? Explain in 2 sentences."}
# ]
# print(chat_cycle(messages)) 

## multi-turn conversation
# conversation = [
#     {"role": "system", "content": "You are a friendly teaching assistant."},
#     {"role": "user", "content": "What is an AI agent?"},
# ]

# reply1 = chat_cycle(conversation)
# print(f"Assistant: {reply1}")
# # Add another turn
# conversation.append({"role": "assistant", "content": reply1})
# conversation.append({"role": "user", "content": "Can you give me an example in healthcare?"})
# reply2 = chat_cycle(conversation)
# print("AI:", reply2)

## Context Window 

# Keep adding user–assistant turns until responses get vague or inconsistent.

# Try copying and pasting a long article as input, then continue the dialogue.

# Observe where the LLM “forgets” early context → this demonstrates context window limits.  


# # Controlled Output Cycles

# messages = [
#     {"role": "system", "content": "You are a html tables-only assistant."},
#     {"role": "user", "content": "List 3 tools used in Agentic AI."}
# ]
# print(chat_cycle(messages))

#Mini Project: Q&A Agent Simulation

conversation = [{"role": "system", "content": "You are an educational AI tutor."}]
 
while True:
    user_input = input("User: ")
    if user_input.lower() in ["exit","quit"]: break
    conversation.append({"role": "user", "content": user_input})
    reply = chat_cycle(conversation)
    print("AI:", reply)
    conversation.append({"role": "assistant", "content": reply})